### ISSUE TITLE
Unable to access to AWS Resources even with correct credentials

### ISSUE THREAD

**Issue by parameshnalla** [Gamesight/aws-glue-local-scala#2]
Hi There, 

First of all, thank you for this contribution. I was trying to use this tool to run one of the aws glue job. My script is accessing the AWS Glue catalog and reading the data from S3. 

I was hitting with AWS 400 error, the same job run on AWS Glue console without any issue, if you have any clue on this error, please help me out. 

` should run the job *** FAILED ***
[info]   com.amazonaws.services.glue.model.EntityNotFoundException: Database local_agarbuz_ds not found. (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 54a5cb9e-8b37-49cb-b14a-d343fd155333; Proxy: null)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
[info]   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)`

**Comment by JeremyDOwens** [comment]
Hi,
Thanks for checking out the repo. My first guess is that the IAM role associated with your CLI access doesn't have full permissions to use AWS Glue. If you could share some of  the Scala code, I might be able to get a better idea.

**Comment by parameshnalla** [comment]
Hi, Jeremy thank you for the quick reply, I just figure out that, my AWS region was set incorrectly, that is the reason it is unable to find glue tables. 

Thank you so much again
